create or replace TABLE RLI_TEST.RAW.CLAIMS (
	CLAIM_ID NUMBER(38,0),
	POLICY_ID NUMBER(38,0),
	CLAIM_DATE DATE,
	CLAIM_AMOUNT NUMBER(38,2),
	CLAIM_STATUS VARCHAR(16777216),
	_INSRT_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);