create or replace TABLE RLI_TEST.RAW.ENDORSEMENTS (
	ENDORSEMENT_AMOUNT NUMBER(38,2),
	ENDORSEMENT_DATE DATE,
	ENDORSEMENT_ID NUMBER(38,0),
	ENDORSEMENT_TYPE VARCHAR(16777216),
	POLICY_ID NUMBER(38,0),
	_INSRT_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);