create or replace TABLE RLI_TEST.RAW.PAYMENTS (
	PAYMENT_ID NUMBER(38,0),
	POLICY_ID NUMBER(38,0),
	PAYMENT_DATE DATE,
	PAYMENT_AMOUNT NUMBER(38,2),
	_INSRT_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);