create or replace TABLE RLI_TEST.RAW.POLICIES (
	POLICY_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	POLICY_TYPE VARCHAR(16777216),
	EFFECTIVE_DATE DATE,
	EXPIRATION_DATE DATE,
	PREMIUM NUMBER(38,2),
	_INSRT_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);